applications:
  - name: django-app
    namespace: default
    project: default
    source:
      repoURL: ${github_repo_url}
      path: lesson-8-9/charts/django-app
      targetRevision: lesson-8-9
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: django-app
    url: ${github_repo_url}
    username: ${github_username}
    password: ${github_token}
    repoConfig:
      insecure: "true"
      enableLfs: "true"